<#
Builds SuperCC.jar from this repo.

IMPORTANT: SuperCC's GUI is built with the IntelliJ GUI Designer (.form files).
Those classes (graphics/Gui + the tools/* dialogs) get a hidden $$$setupUI$$$()
method generated by IntelliJ's *form compiler* at build time — plain javac does
NOT produce it, so a full javac rebuild yields a jar whose GUI dies on launch
("... playButton is null"). So the compiled classes shipped in the jar are the
authoritative IntelliJ-built baseline (committed under emulator/ game/ graphics/
io/ tools/ util/), and this build only RECOMPILES the hand-edited, non-form
source files listed below and splices them over that baseline.

  --> If you mod a NEW source file, add it to $MODIFIED (and make sure it has no
      sibling .form file, or you'll break its GUI).

Requires a JDK 16+. Usage:  powershell -ExecutionPolicy Bypass -File build.ps1 [-Out SuperCC.jar]

  -Package  also assembles the release zip that gets attached to the GitHub
            release: dist\SuperCC-<tag>.zip holding SuperCC.jar, a STOCK
            succ_settings.ini and README.txt. The tag is read out of
            SuperCC.java's BUILD_TAG, and the .ini is generated by calling
            SuccPaths.createSettingsFile() in the jar that was just built --
            never hand-written -- so the shipped file is exactly the file
            SuperCC itself would create, defaults and layout included.
#>
param([string]$Out = "SuperCC.jar", [switch]$Package)
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

# Hand-edited source files to recompile & splice (relative to java/). None are .form-based.
$MODIFIED = @(
    "emulator\SuperCC.java",
    "graphics\LevelPanel.java",
    "graphics\MenuBar.java",
    "graphics\GamePanel.java",
    "io\LevelFactory.java",
    "io\SuccPaths.java",
    "io\TWSWriter.java"
)

# The Oracle "javapath" dir on PATH exposes javac/java but not jar; resolve a real JDK bin.
function Find-JdkBin {
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin\jar.exe"))) { return (Join-Path $env:JAVA_HOME "bin") }
    $cand = Get-ChildItem "C:\Program Files\Java" -Directory -ErrorAction SilentlyContinue |
            Where-Object { Test-Path (Join-Path $_.FullName "bin\jar.exe") } |
            Sort-Object Name -Descending | Select-Object -First 1
    if ($cand) { return (Join-Path $cand.FullName "bin") }
    throw "No JDK with jar.exe found. Set JAVA_HOME to a JDK 16+."
}
$jdkBin = Find-JdkBin
$javac  = Join-Path $jdkBin "javac.exe"
$jar    = Join-Path $jdkBin "jar.exe"

$stage = Join-Path $env:TEMP ("scc-build-" + [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Force -Path $stage | Out-Null
try {
    # Stage the FULL jar content: pristine compiled classes + libs + resources + source + manifest.
    foreach ($d in "com","org","emulator","game","graphics","io","tools","util","resources","java","META-INF") {
        $src = Join-Path $root $d
        if (Test-Path $src) { robocopy $src (Join-Path $stage $d) /E /NFL /NDL /NJH /NJS /NP | Out-Null }
    }
    # For each modified class, drop its baseline .class (incl. inner classes) so the recompile is clean.
    $srcFiles = @()
    foreach ($m in $MODIFIED) {
        $pkg  = Split-Path $m
        $base = [IO.Path]::GetFileNameWithoutExtension($m)
        $dir  = Join-Path $stage $pkg
        if (Test-Path $dir) {
            Get-ChildItem $dir -File -Filter "*.class" |
                Where-Object { $_.Name -eq "$base.class" -or $_.Name.StartsWith($base + '$') } |
                ForEach-Object { [IO.File]::Delete($_.FullName) }
        }
        $srcFiles += (Join-Path $root (Join-Path "java" $m))
    }
    # Recompile ONLY those files; -implicit:none + empty sourcepath so javac never touches the
    # form-based classes (their pristine .class on -cp are used for references).
    $empty = Join-Path $stage "__empty"; New-Item -ItemType Directory -Force $empty | Out-Null
    & $javac --release 16 -encoding UTF-8 -cp $stage -sourcepath $empty -implicit:none -d $stage @srcFiles
    if ($LASTEXITCODE -ne 0) { throw "javac failed (exit $LASTEXITCODE)" }
    [IO.Directory]::Delete($empty, $true)
    # Package.
    $outPath = Join-Path $root $Out
    if ([IO.File]::Exists($outPath)) { [IO.File]::Delete($outPath) }
    & $jar cfm $outPath (Join-Path $stage "META-INF\MANIFEST.MF") -C $stage .
    if ($LASTEXITCODE -ne 0) { throw "jar failed (exit $LASTEXITCODE)" }
    Write-Host ("Built {0} ({1:N0} bytes)" -f $outPath, (Get-Item $outPath).Length)

    if ($Package) {
        # The build tag is the single source of truth for the release name.
        $sccSrc = Get-Content (Join-Path $root "java\emulator\SuperCC.java") -Raw
        if ($sccSrc -notmatch 'BUILD_TAG\s*=\s*"\[(?<tag>[^\]]+)\]"') { throw "Could not read BUILD_TAG out of SuperCC.java" }
        $tag = $Matches['tag']

        # Wipe the whole dist folder, not just this tag's staging dir. Two reasons: a package run
        # that fails partway used to leave the PREVIOUS zip sitting next to a half-built staging
        # folder under the same name, looking current; and dist\ otherwise accumulates every old tag.
        $dist = Join-Path $root "dist"
        if (Test-Path $dist) { Remove-Item -LiteralPath $dist -Recurse -Force }
        $pkgDir = Join-Path $dist "SuperCC-$tag"
        New-Item -ItemType Directory -Force -Path $pkgDir | Out-Null

        # Generate succ_settings.ini THROUGH THE JAR, so it cannot drift from what the program
        # writes. createSettingsFile() refuses to overwrite, hence the empty directory above.
        $genSrc = Join-Path $stage "MakeStockSettings.java"
        $iniPath = Join-Path $pkgDir "succ_settings.ini"
        @"
import io.SuccPaths;
import java.io.File;
public class MakeStockSettings {
    public static void main(String[] a) throws Exception { SuccPaths.createSettingsFile(new File(a[0])); }
}
"@ | Set-Content -Path $genSrc -Encoding ASCII   # ASCII on purpose: PS 5.1's utf8 writes a BOM, and javac chokes on one
        & $javac -cp $outPath -d $stage $genSrc
        if ($LASTEXITCODE -ne 0) { throw "could not compile the settings generator (exit $LASTEXITCODE)" }
        & (Join-Path $jdkBin "java.exe") -cp "$outPath;$stage" MakeStockSettings $iniPath
        if ($LASTEXITCODE -ne 0) { throw "could not generate succ_settings.ini (exit $LASTEXITCODE)" }
        if (-not (Test-Path $iniPath)) { throw "the settings generator reported success but wrote no file" }

        Copy-Item $outPath (Join-Path $pkgDir "SuperCC.jar") -Force

        # README goes in with CRLF, because it is read in Notepad on Windows. Normalizing here and
        # not relying on .gitattributes is deliberate: eol=crlf only applies at checkout, so a
        # working tree written by anything else would otherwise ship LF. Idempotent (LF -> LF -> CRLF).
        # NOTE: succ_settings.ini gets NO such treatment. Its mixed layout (platform separator after
        # a section header, bare \n after a key line) is what SuperCC itself writes, and matching it
        # byte for byte is what stops the first settings change from rewriting the whole file.
        $readme = [IO.File]::ReadAllText((Join-Path $root "README.txt"))
        $readme = $readme -replace "`r`n", "`n" -replace "`n", "`r`n"
        [IO.File]::WriteAllText((Join-Path $pkgDir "README.txt"), $readme, (New-Object Text.UTF8Encoding $false))

        # GPLv2+ binary distribution: the license text travels WITH the binary, not just in the repo.
        Copy-Item (Join-Path $root "COPYING") (Join-Path $pkgDir "COPYING") -Force

        # The README must describe the build it ships with, or the download lies about itself.
        # Anchored to the HEADER LINE specifically: a loose "appears anywhere" test would be
        # satisfied by a revision-history entry mentioning the tag while the header still named
        # the previous build.
        $readmeHead = (Get-Content (Join-Path $pkgDir "README.txt") -TotalCount 5) -join "`n"
        if ($readmeHead -notmatch ("(?m)^.*build\s+" + [regex]::Escape($tag) + "\s*$")) {
            throw "README.txt's header does not name build $tag -- update it before packaging"
        }

        # Entry names are built BY HAND with forward slashes, and this is not fussiness.
        # The zip spec (APPNOTE 4.4.17.1) requires "/". On PowerShell 5.1 / .NET Framework BOTH
        # Compress-Archive AND ZipFile::CreateFromDirectory emit "SuperCC-<tag>\README.txt" with a
        # BACKSLASH -- verified here, not assumed. Explorer and 7-Zip tolerate it; Info-ZIP `unzip`
        # on Linux/macOS and Java's ZipInputStream do NOT treat "\" as a separator and instead
        # produce files with literal backslashes in their names and no folder at all. This is a
        # public download, so it has to open correctly off Windows. CreateEntryFromFile uses the
        # name it is given verbatim, which is the only reliable lever on this runtime.
        $zip = Join-Path $dist "SuperCC-$tag.zip"
        # BOTH assemblies: ZipFile/ZipFileExtensions live in System.IO.Compression.FileSystem, but
        # the ZipArchiveMode enum lives in System.IO.Compression. Loading only the first gives
        # "Unable to find type [IO.Compression.ZipArchiveMode]" on PowerShell 5.1.
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        Add-Type -AssemblyName System.IO.Compression
        $archive = [IO.Compression.ZipFile]::Open($zip, [IO.Compression.ZipArchiveMode]::Create)
        try {
            foreach ($f in (Get-ChildItem -LiteralPath $pkgDir -File | Sort-Object Name)) {
                [IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
                    $archive, $f.FullName, "SuperCC-$tag/$($f.Name)",
                    [IO.Compression.CompressionLevel]::Optimal) | Out-Null
            }
        } finally { $archive.Dispose() }
        # Verify the ARCHIVE, not the folder it was built from -- the zip is what people download,
        # and it is the last thing to go wrong. Three gates: conformant entry names, the exact
        # expected file set, and every entry byte-identical to its source (so the zip can never
        # ship a jar or an ini that disagrees with the build that just ran).
        $expected = @{}
        foreach ($f in (Get-ChildItem -LiteralPath $pkgDir -File)) {
            $expected["SuperCC-$tag/$($f.Name)"] = (Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash
        }
        $check = [IO.Compression.ZipFile]::OpenRead($zip)
        try {
            $bad = @($check.Entries | Where-Object { $_.FullName -match '\\' })
            if ($bad.Count -gt 0) { throw "$($bad.Count) zip entry name(s) contain a backslash -- the archive would not extract correctly off Windows" }
            $names = @($check.Entries | ForEach-Object { $_.FullName } | Sort-Object)
            $want  = @($expected.Keys | Sort-Object)
            if (Compare-Object $names $want) { throw "zip contents do not match the staged folder.`n  in zip: $($names -join ', ')`n  wanted: $($want -join ', ')" }
            foreach ($e in $check.Entries) {
                $s = $e.Open(); $ms = New-Object IO.MemoryStream; $s.CopyTo($ms); $s.Close()
                $sha = [Security.Cryptography.SHA256]::Create()
                $got = [BitConverter]::ToString($sha.ComputeHash($ms.ToArray())).Replace('-','')
                $ms.Dispose()
                if ($got -ne $expected[$e.FullName]) { throw "zip entry $($e.FullName) does not match the file it was built from" }
            }
        } finally { $check.Dispose() }
        Write-Host ("Packaged {0} ({1:N0} bytes)" -f $zip, (Get-Item $zip).Length)
        Get-ChildItem $pkgDir | ForEach-Object { Write-Host ("    {0,-20} {1,10:N0} bytes" -f $_.Name, $_.Length) }
    }
} finally {
    [IO.Directory]::Delete($stage, $true)
}
