<#
Builds SuperCC.jar from this repo.

IMPORTANT: SuperCC's GUI is built with the IntelliJ GUI Designer (.form files).
Those classes (graphics/Gui + the tools/* dialogs) get a hidden $$$setupUI$$$()
method generated by IntelliJ's *form compiler* at build time — plain javac does
NOT produce it, so a full javac rebuild yields a jar whose GUI dies on launch
("... playButton is null"). So the compiled classes shipped in the jar are the
authoritative IntelliJ-built baseline (committed under emulator/ game/ graphics/
io/ tools/ util/), and this build only RECOMPILES the hand-edited, non-form
source files listed below and splices them over that baseline.

  --> If you mod a NEW source file, add it to $MODIFIED (and make sure it has no
      sibling .form file, or you'll break its GUI).

Requires a JDK 16+. Usage:  powershell -ExecutionPolicy Bypass -File build.ps1 [-Out SuperCC.jar]
#>
param([string]$Out = "SuperCC.jar")
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot

# Hand-edited source files to recompile & splice (relative to java/). None are .form-based.
$MODIFIED = @(
    "emulator\SuperCC.java",
    "graphics\LevelPanel.java",
    "graphics\MenuBar.java",
    "graphics\GamePanel.java",
    "io\LevelFactory.java",
    "io\SuccPaths.java",
    "io\TWSWriter.java"
)

# The Oracle "javapath" dir on PATH exposes javac/java but not jar; resolve a real JDK bin.
function Find-JdkBin {
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin\jar.exe"))) { return (Join-Path $env:JAVA_HOME "bin") }
    $cand = Get-ChildItem "C:\Program Files\Java" -Directory -ErrorAction SilentlyContinue |
            Where-Object { Test-Path (Join-Path $_.FullName "bin\jar.exe") } |
            Sort-Object Name -Descending | Select-Object -First 1
    if ($cand) { return (Join-Path $cand.FullName "bin") }
    throw "No JDK with jar.exe found. Set JAVA_HOME to a JDK 16+."
}
$jdkBin = Find-JdkBin
$javac  = Join-Path $jdkBin "javac.exe"
$jar    = Join-Path $jdkBin "jar.exe"

$stage = Join-Path $env:TEMP ("scc-build-" + [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Force -Path $stage | Out-Null
try {
    # Stage the FULL jar content: pristine compiled classes + libs + resources + source + manifest.
    foreach ($d in "com","org","emulator","game","graphics","io","tools","util","resources","java","META-INF") {
        $src = Join-Path $root $d
        if (Test-Path $src) { robocopy $src (Join-Path $stage $d) /E /NFL /NDL /NJH /NJS /NP | Out-Null }
    }
    # For each modified class, drop its baseline .class (incl. inner classes) so the recompile is clean.
    $srcFiles = @()
    foreach ($m in $MODIFIED) {
        $pkg  = Split-Path $m
        $base = [IO.Path]::GetFileNameWithoutExtension($m)
        $dir  = Join-Path $stage $pkg
        if (Test-Path $dir) {
            Get-ChildItem $dir -File -Filter "*.class" |
                Where-Object { $_.Name -eq "$base.class" -or $_.Name.StartsWith($base + '$') } |
                ForEach-Object { [IO.File]::Delete($_.FullName) }
        }
        $srcFiles += (Join-Path $root (Join-Path "java" $m))
    }
    # Recompile ONLY those files; -implicit:none + empty sourcepath so javac never touches the
    # form-based classes (their pristine .class on -cp are used for references).
    $empty = Join-Path $stage "__empty"; New-Item -ItemType Directory -Force $empty | Out-Null
    & $javac --release 16 -encoding UTF-8 -cp $stage -sourcepath $empty -implicit:none -d $stage @srcFiles
    if ($LASTEXITCODE -ne 0) { throw "javac failed (exit $LASTEXITCODE)" }
    [IO.Directory]::Delete($empty, $true)
    # Package.
    $outPath = Join-Path $root $Out
    if ([IO.File]::Exists($outPath)) { [IO.File]::Delete($outPath) }
    & $jar cfm $outPath (Join-Path $stage "META-INF\MANIFEST.MF") -C $stage .
    if ($LASTEXITCODE -ne 0) { throw "jar failed (exit $LASTEXITCODE)" }
    Write-Host ("Built {0} ({1:N0} bytes)" -f $outPath, (Get-Item $outPath).Length)
} finally {
    [IO.Directory]::Delete($stage, $true)
}
